version: 2

updates:
  # --- Python dependencies ---
  - package-ecosystem: "pip"
    directory: "/"          
    schedule:
      interval: "daily"
    labels:
      - "dependencies"

  # --- GitHub Actions updates ---
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"


    # --- GitHub docker updates ---
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
